version: '3.6'
services:
  do-blog-learn-graphql-by-doing:
    image: hasura/graphql-engine:v2.0.0-alpha.2
    depends_on:
    - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/do_blog_learn_graphql_by_doing
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
