version: '3.6'
services:
  postgres:
    image: postgres:12.3
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgrespassword
    volumes:
    - db_data:/var/lib/postgresql/data
  caddy:
    image: abiosoft/caddy:0.11.1
    restart: always
    env_file: caddy.env
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./Caddyfile:/etc/Caddyfile
    - caddy_certs:/root/.caddy
    - ./index.html:/html/index.html
volumes:
  db_data:
  caddy_certs:
