version: '3.6'
services:
  tic-tac-toe-react-remote-schema:
    restart: always
    image: tic-tac-toe-react-remote-schema
    ports:
    - "9020:4000"
    environment:
      POSTGRES_CONNECTION_STRING: postgres://postgres:@postgres:5432/tic_tac_toe_react
    build: repos/graphql-engine/community/sample-apps/tic-tac-toe-react/remote-schema
  tic-tac-toe-ui:
    restart: always
    image: tic-tac-toe-ui
    build: repos/graphql-engine/community/sample-apps/tic-tac-toe-react/client
