version: '3.6'
services:
  whatsapp-clone-ui:
    restart: always
    image: whatsapp-clone-ui
    env_file: whatsapp-clone.env  
    build: repos/graphql-engine/community/sample-apps/whatsapp-clone-typescript-react/react-app
  whatsapp-clone-auth:
    restart: always
    image: whatsapp-clone-auth
    env_file: whatsapp-clone.env  
    build: repos/graphql-engine/community/sample-apps/whatsapp-clone-typescript-react/auth-server
    environment:
      DATABASE_URL: postgres://postgres:@postgres:5432/whatsapp_clone
